FROM {{ $.source }}
LABEL maintainer="cookeem"
LABEL email="cookeem@qq.com"
RUN adduser -u 1000 -D dory && sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && apk --update add curl gcc musl-dev
